### ISSUE TITLE
error occur

### ISSUE THREAD

**Issue by kazuminn** [agatan/vim-slaq#1]
I use this plugin.

but ,error occure.

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun 19 2015 22:58:16)
MacOS X (unix) 

<pre>
E121: 未定義の変数です: s:save_cpo
E15: 無効な式です: s:save_cpo
行  170:
</pre>

why?

**Comment by agatan** [comment]
Thanks for your report!

Actually, this repository is private and experimental, so I didn't fix it.

Now, I tried to modify a few points in `autoload/slaq.vim`, but I couldn't fix it...

I think that `autoload/slaq.vim` is loaded from `autoload/slaq.vim` recursively. 
Do you know whether my opinion is correct ?

This script is my first VimL app, so I want some advice...

**Comment by kazuminn** [comment]
Probably,

error's cause is scope miss.

thus b:.

Because channel_history function create new buffe,  must share channnel_name variable between two buffe.

so,spred channnel_name variable scope

**Comment by kazuminn** [comment]
うーん。私もわかんないです。

lingr vimの方に気軽に質問してみるのがいいかもしれませんね。

**Comment by agatan** [comment]
script localな値とautoloadが絡んだ時の挙動がイマイチ把握できていないので直せないです...
そうですね...ちょっと適当なときに聞いてみます. autoloadで読まれるファイルに初期化処理を書く方法もよくわからないのでそれも合わせて
報告&アドバイスありがとうございます！
